api_version = "2026-07"

[[extensions]]
name = "Creator Program"
handle = "creator-program"
uid = "3f44f7e0-6774-1ec2-165a-a1624410aa06ec2c82f3"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/CreatorProgram.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
network_access = true
